apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-demo-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/c0ckr0ach/k8s-demo.git
    targetRevision: main
    path: gitops/charts/k8s-demo-app
    helms:
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true