global:
  environment: default

backend:
  replicaCount: 1
  image:
    repository: backend
    tag: v1
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  probes:
    liveness:
      path: /healthz
      initialDelaySeconds: 5
      periodSeconds: 10
    readiness:
      path: /healthz
      initialDelaySeconds: 5
      periodSeconds: 10

frontend:
  replicaCount: 1
  image:
    repository: frontend
    tag: v1
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  resources:
    limits:
      cpu: 100m
      memory: 64Mi
    requests:
      cpu: 25m
      memory: 32Mi

redis:
  image:
    repository: redis
    tag: 7.2-alpine
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 6379

ingress:
  enabled: true
  className: nginx